# Generated by Django 4.0.2 on 2022-04-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel_Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField()),
                ('Entered_boy_girl_name', models.TextField()),
                ('Entered_boy_girl_roll_no', models.IntegerField()),
                ('Host_boy_girl_name', models.TextField()),
                ('Host_boy_girl_roll_no', models.IntegerField()),
                ('Room_no', models.TextField()),
                ('Date', models.TextField()),
                ('Entry', models.TextField()),
                ('Exit', models.TextField(default='not filled')),
            ],
        ),
    ]
